"""Database models (SQLModel).

Table models for the backend. Primary keys are **UUIDv7** generated by the
stdlib ``uuid.uuid7`` (Python 3.14+): they are time-ordered, so rows sort by
creation order and index locality stays good — unlike random UUIDv4.
"""

from datetime import UTC, datetime
from uuid import UUID, uuid7

from sqlalchemy import JSON, Column
from sqlmodel import Field, SQLModel


class Result(SQLModel, table=True):
    """A logged reflection result."""

    __tablename__ = "results"

    id: UUID = Field(default_factory=uuid7, primary_key=True)
    reflection_id: str = Field(index=True)
    # The day the result is logged for, "YYYY-MM-DD" (distinct from created_at).
    date: str = Field(index=True)
    # JSON-shaped payloads stored as a JSON column.
    answers: dict[str, object] = Field(default_factory=dict, sa_column=Column(JSON))
    matched_types: list[str] = Field(default_factory=list, sa_column=Column(JSON))
    created_at: datetime = Field(default_factory=lambda: datetime.now(UTC))
    updated_at: datetime = Field(default_factory=lambda: datetime.now(UTC))
